name: New issue!

on: 
  issues:
    types: [opened]

jobs:
  print-issue:
    runs-on: ubuntu-latest
    steps:
      - name: "Put some info on the screen!w"
        run: |
          echo "Brand new issue, pain in the ass."
          echo "The pain is called: ${{ github.event.issue.title }}"